[Service]
Host = "localhost"
Port = 4000
Labels = []
OpenMsg = "edgeX ui started"
StaticResourcesPath = "./static"

#Using an default memory db automatically if not configed here.
[Database]
Host = "localhost"
Name = "edgex-ui-go"
Port = 27017
Username = "su"
Password = "su"
  [Database.Scheme]
  User = "user"
  Gateway = "gateway"

[DynamicProxy]
CoreDataPath     = "/core-data"
CoreDataPort     = "48080"
CoreDataUri      = ""
CoreMetadataPath = "/core-metadata"
CoreMetadataPort = "48081"
CoreMetadataUri  = ""
CoreCommandPath  = "/core-command"
CoreCommandPort  = "48082"
CoreCommandUri   = ""
CoreExportPath   = "/core-export"
CoreExportPort   = "48071"
CoreExportUri    = ""
RuleEnginePath   = "/rule-engine"
RuleEnginePort   = "48075"
RuleEngineUri    = ""
SupportLoggingPath   = "/support-logging"
SupportLoggingPort   = "48061"
SupportLoggingUri    = ""
SupportNotificationPath   = "/support-notification"
SupportNotificationPort   = "48060"
SupportNotificationUri    = ""
SupportSchedulerPath   = "/support-scheduler"
SupportSchedulerPort   = "48085"
SupportSchedulerUri    = ""
